services:
  godev:
    build: .
    volumes:
      # WSLg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      # Selenium
      - /dev/shm:/dev/shm
      - selenium/standalone-chrome:4.8.1-20230221
    environment:
      # WSLg
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    ports:
      # Selenium
      - "4444:4444"
# ここから一致
